    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-heading">
                    <a id="logo" href="<?php echo BASE; ?>">
                        <img class="img-responsive" src="<?php echo IMG; ?>logo.png" alt="">
                    </a>
                </div>
                <div class="panel-body">
                    <h2 class="alert alert-success">
                        <font color= #088A4B > <center><b> Seja bem-vindo a TravelTours!</b></center></font>
                    </h2>
                    <p style="font-size:19px">
                        É necessário fazer o <a style="font-size:18px" class="btn btn-success btn-xs" href="<?php echo BASE; ?>/login/index.phtml" title="Click aqui e faça seu Login. " target="_blank">Login</a> para continuar fazendo o uso dessa ferramenta. 
                        Caso ainda não tenha, <a style="font-size:18px" class="btn btn-success btn-xs" href="<?php echo BASE; ?>/cadastro/index.phtml" title="Click aqui e faça seu Cadastro." target="_blank">cadastre-se</a>.
                    </p>
                </div>
            </div>
        </div>
    </div>
