<!doctype html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta name="author" content="Leonardo P. de Vasconcelos">
	<meta name="generator" content="TravelTours">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>TravelTours</title>
	<link rel="shortcut icon" href="<?php echo IMG; ?>favicon1.ico" type="image/x-icon">
	<link rel="stylesheet" href="<?php echo CSS; ?>bootstrap.min.css" type="text/css">
	<link rel="stylesheet" href="<?php echo CSS; ?>main.css" type="text/css">
	<?php 
		echo $add_css;
		echo $add_js;
	?>
</head>
<body>
	<div class="container">